### ISSUE TITLE
Need to re-structure the parts of the story so that they flow sequentially

### ISSUE THREAD

**Issue by mariannegoldin** [mariannegoldin/itc134-a3-grp7#14]

**Comment by theemmanuelle** [comment]
Re-wrote part of the body of the story for sequential flow.

**Comment by theemmanuelle** [comment]
@EveCCCCC  @Aaron-SCC  Please feel free to tweak the writing to ensure that your voice is maintained.

**Comment by Aaron-SCC** [comment]
triage initiated.

**Comment by Aaron-SCC** [comment]
Please see updated file:
    AARON_NEWFILE.txt
for this issue...
